apiVersion: v1
kind: Service
metadata:
  name: airbyte-webapp-svc
spec:
  type: ClusterIP
  ports:
    - port: 80
      protocol: TCP
  selector:
    airbyte: webapp
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: airbyte-webapp
spec:
  replicas: 1
  selector:
    matchLabels:
      airbyte: webapp
  template:
    metadata:
      labels:
        airbyte: webapp
        use-default-egress-policy: "true"
        allow-to-apiserver: "true"
    spec:
      containers:
        - name: airbyte-webapp-container
          image: docker-horizon-snapshot.dr-uw2.adobeitc.com/azheng/airbyte/webapp
          env:
            - name: AIRBYTE_VERSION
              valueFrom:
                configMapKeyRef:
                  name: airbyte-env
                  key: AIRBYTE_VERSION
            - name: API_URL
              valueFrom:
                configMapKeyRef:
                  name: airbyte-env
                  key: API_URL
            - name: TRACKING_STRATEGY
              valueFrom:
                configMapKeyRef:
                  name: airbyte-env
                  key: TRACKING_STRATEGY
            - name: FULLSTORY
              valueFrom:
                configMapKeyRef:
                  name: airbyte-env
                  key: FULLSTORY
            - name: IS_DEMO
              valueFrom:
                configMapKeyRef:
                  name: airbyte-env
                  key: IS_DEMO
            - name: INTERNAL_API_HOST
              valueFrom:
                configMapKeyRef:
                  name: airbyte-env
                  key: INTERNAL_API_HOST
          ports:
            - containerPort: 80
#---
#apiVersion: networking.k8s.io/v1
#kind: Ingress
#metadata:
#  name: airbyte-webapp-ingress
#spec:
#  defaultBackend:
#    service:
#      name: airbyte-webapp-svc
#      port:
#        number: 80